services:
    app.menu_builder:
        class: Epsi\PageBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", '@doctrine.orm.entity_manager']

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main }